app: auth-micro
service: auth-micro

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: "20201221"
  region: eu-west-1
  environment:
    VAULT_ADDR: https://vault-public-vault-577e1858.573e57b9.z1.hashicorp.cloud:8200
    VAULT_NAMESPACE: admin

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: "*"
      - http:
          path: /login
          method: ANY
          cors:
            origin: "*"
      - http:
          path: /signup
          method: ANY
          cors:
            origin: "*"
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
